image: docker:git
services:
  - docker:dind

stages:
  - build
  - release

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE: registry.gitlab.com/jaxnet/jaxnetd/$CI_COMMIT_REF_NAME:latest

.before_script: &before_script
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-hub -y )'
    - eval $(ssh-agent -s)
    - echo "$JAX_KEY" > ./key.file
    - chmod 400 ./key.file
    - ssh-add ./key.file
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-keyscan -t rsa discretemind.com >> ~/.ssh/known_hosts

build:docker:
  stage: build
  <<: *before_script
  only:
    - master
    - dev
  tags:
    - shell
  script:
    - docker build --pull -t $IMAGE .
    - docker push $IMAGE

build:release:
  stage: build
  image:
    name: goreleaser/goreleaser
    entrypoint: [ "" ]
  before_script:
    - echo Just to replace default
  script:
    - goreleaser release --snapshot --rm-dist
  tags:
    - docker
  artifacts:
    paths:
      - dist
  only:
    - master

release:
  stage: release
  image:
    name: goreleaser/goreleaser:latest
    entrypoint: [ "" ]
  variables:
    GITLAB_TOKEN: $CI_ACCESS_TOKEN
  before_script:
    - apk add build-base
  script:
    - goreleaser release --rm-dist
  tags:
    - docker
  only:
    refs:
      - tags
