# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - main: ./cmd/jaxctl
    id: "jaxctl"
    binary: jaxctl
    ldflags:
      - -s -w -X gitlab.com/jaxnet/jaxnetd/version.tag={{.Version}}
        -X gitlab.com/jaxnet/jaxnetd/version.commit={{.Commit}}
        -X gitlab.com/jaxnet/jaxnetd/version.date={{.Date}}
        -X gitlab.com/jaxnet/jaxnetd/version.builtBy=goreleaser
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - jaxnetd.testnet.yaml
      - docs/*

nfpms:
  - maintainer: JAX.Net Devs <dev@jax.net>
    description: The JAX.Network node
    homepage: https://jax.network
    license: ISC
    formats:
      - deb
      - rpm
      - apk

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
