# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
# disable because of https://gitlab.com/jaxnet/jaxnetd/-/issues/26
#      - arm64

  - main: ./cmd/jaxctl
    id: "jaxctl"
    binary: jaxctl
    ldflags:
      - -s -w -X gitlab.com/jaxnet/jaxnetd/version.tag={{.Version}}
        -X gitlab.com/jaxnet/jaxnetd/version.commit={{.Commit}}
        -X gitlab.com/jaxnet/jaxnetd/version.date={{.Date}}
        -X gitlab.com/jaxnet/jaxnetd/version.builtBy=goreleaser
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
#      - arm64

  - main: ./database/cmd/dbtool
    id: "jaxnet-db-tool"
    binary: "jaxnet-db-tool"
    ldflags:
      - -s -w -X gitlab.com/jaxnet/jaxnetd/version.tag={{.Version}}
        -X gitlab.com/jaxnet/jaxnetd/version.commit={{.Commit}}
        -X gitlab.com/jaxnet/jaxnetd/version.date={{.Date}}
        -X gitlab.com/jaxnet/jaxnetd/version.builtBy=goreleaser
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

  - main: ./database/cmd/inspector
    id: "jaxnet-db-inspector"
    binary: "jaxnet-db-inspector"
    ldflags:
      - -s -w -X gitlab.com/jaxnet/jaxnetd/version.tag={{.Version}}
        -X gitlab.com/jaxnet/jaxnetd/version.commit={{.Commit}}
        -X gitlab.com/jaxnet/jaxnetd/version.date={{.Date}}
        -X gitlab.com/jaxnet/jaxnetd/version.builtBy=goreleaser
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

  - main: ./cmd/genaddr
    id: "jaxnet-genaddr"
    binary: "jaxnet-genaddr"
    ldflags:
      - -s -w -X gitlab.com/jaxnet/jaxnetd/version.tag={{.Version}}
        -X gitlab.com/jaxnet/jaxnetd/version.commit={{.Commit}}
        -X gitlab.com/jaxnet/jaxnetd/version.date={{.Date}}
        -X gitlab.com/jaxnet/jaxnetd/version.builtBy=goreleaser
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

  - main: ./cmd/difficulty-calc
    id: "jaxnet-difficulty-calc"
    binary: "jaxnet-difficulty-calc"
    ldflags:
      - -s -w -X gitlab.com/jaxnet/jaxnetd/version.tag={{.Version}}
        -X gitlab.com/jaxnet/jaxnetd/version.commit={{.Commit}}
        -X gitlab.com/jaxnet/jaxnetd/version.date={{.Date}}
        -X gitlab.com/jaxnet/jaxnetd/version.builtBy=goreleaser
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - jaxnetd.testnet.toml
      - jaxnetd.mainnet.toml
      - docs/*

nfpms:
  - maintainer: JAX.Net Devs <dev@jax.net>
    description: The JAX.Network node
    homepage: https://jax.network
    license: ISC
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: ./jaxnetd.mainnet.toml
        dst: /etc/jaxnetd.mainnet.toml
        type: config
      - src: ./jaxnetd.testnet.toml
        dst: /etc/jaxnetd.testnet.toml
        type: config
      - src: ./scripts/jaxnetd-monitor.service
        dst: /lib/systemd/system/jaxnetd-monitor.service
    scripts:
      postinstall: package_scripts/post-install.sh

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
