data_dir = "jaxnetd-data/data"
log_dir = "jaxnetd-data/logs"
debug_level = "info"

[node]
net = "testnet"

[node.p2p]
listeners = ["0.0.0.0:18444"]
peers = [
    "164.90.150.0:18444",
    "128.199.31.83:18444",
    "138.68.152.77:18444",
    "159.89.89.207:18444"
]

[node.rpc]
disable = false
user = "jax"
password = "aWeSoMePaSss"
maxclients = 1_000
listeners = ["0.0.0.0:18333"]

[node.shards]
enable = true
autorun = true

[node.beacon_chain]
tx_index = true
addr_index = true
auto_expand = true
expansion_rule = 1
expansion_limit = 2
max_peers = 1_000
no_relay_priority = true
mining_addresses = ["mxQsksaTJb11i7vSxAUL6VBjoQnhP3bfFz"]

[metrics]
enable = false
port = 18_222
