data_dir = "jaxnetd-data/data"
debug_level = "info"

[node]
net = "testnet"

[node.p2p]
listeners = ["0.0.0.0:18444"]
peers = []

[node.rpc]
disable = false
user = "jax"
password = "aWeSoMePaSss"
maxclients = 1_000
listeners = ["0.0.0.0:18333"]

[node.shards]
enable = true
autorun = true

[node.beacon_chain]
tx_index = true
addr_index = true
auto_expand = true
expansion_rule = 1
expansion_limit = 2
max_peers = 1_000
no_relay_priority = true
# PUT YOUR MINITNG ADDRESS
mining_addresses = ["mxQs..."]

[metrics]
enable = false
port = 18_222
