net: fastnet

#node_rpc:
#  host: 116.202.107.209:18333
#  user: jaxnetrpc
#  pass: AUL6VBjoQnhP3bfFzl
node_rpc:
  host: 127.0.0.1:18333
  user: somerpc
  pass: somerpc

cmd:
  send_txs:
    sender_secret: 3c83b4d5645075c9afac0626e8844007c70225f6625efaeac5999529eb8d791b
    destinations:
      - address: minPGY4BWGhNoSofaVow4GvPpMX5bmMTbR
        amount: 300_0000_0000
        shard_id: 1
      - address: mjzVajkZXTLL2RFdcjjcDRAsdEHWPhJNDN
        amount: 300_0000_0000
        shard_id: 2
      - address: msSscKBtjgj7a9dLcfBW5UTrqSyMKCKpf1
        amount: 300_0000_0000
        shard_id: 2
      - address: mqwTzSwf31g5UTp5dou6YkzovGSYjQFmYG
        amount: 300_0000_0000
        shard_id: 2
