# tx-gatling
net: testnet

node_rpc:
  host: 127.0.0.1:28334
  user: somerpc
  pass: somerpc

#data_file: ./data/miner_utxo.csv
#miner
#sender_secret: 3c83b4d5645075c9afac0626e8844007c70225f6625efaeac5999529eb8d791b
# to alice
#destinations:
#  - address: myGdvt6vRNgrFZFtU5FNhW5gxwRqKBcLGv
#    amount: 2500000000
#  - address: myGdvt6vRNgrFZFtU5FNhW5gxwRqKBcLGv
#    amount: 135_0000_0000
#  - address: myGdvt6vRNgrFZFtU5FNhW5gxwRqKBcLGv
#    amount: 75_0000_0000
#  - address: myGdvt6vRNgrFZFtU5FNhW5gxwRqKBcLGv
#    amount: 100_0000_0000
#  - address: myGdvt6vRNgrFZFtU5FNhW5gxwRqKBcLGv
#    amount: 10_0000_0000
#  - address: myGdvt6vRNgrFZFtU5FNhW5gxwRqKBcLGv
#    amount: 1_0000_0000
#  - address: myGdvt6vRNgrFZFtU5FNhW5gxwRqKBcLGv
#    amount: 50_0000_0000

data_file: ./data/alice_utxo.csv
#alice
sender_secret: 6443fb332e1cbfe456674aacf2be1327b6f9fc9c782061ee04ca35e17608d651
# to multisig
destinations:
  - address: 2NCEExe7MBQw6dexbSeyBDca16rP7cgnWgZ
    amount: 36000000000
#
